insert into adv_attrname (attrname_id, attrname) values (1010, "language");
insert into adv_attrname (attrname_id, attrname) values (1109, "lat");
insert into adv_attrname (attrname_id, attrname) values (1110, "lon");
insert into adv_attrname (attrname_id, attrname) values (1112, "utcoffset");
delete from adv_attrname where attrname_id between 1 and 99;
delete from adv_attrname where attrname_id between 1004 and 1006;
delete from adv_attrname where attrname_id between 1401 and 1416;
insert into adv_attrname (attrname_id, attrname) values (1401, 'uploadBuyerUID');
insert into adv_attrname (attrname_id, attrname) values (1402, 'uploadUserID');
insert into adv_attrname (attrname_id, attrname) values (1403, 'uploadIP');
insert into adv_attrname (attrname_id, attrname) values (1404, 'uploadIFA');
insert into adv_attrname (attrname_id, attrname) values (1405, 'uploadDID');
insert into adv_attrname (attrname_id, attrname) values (1406, 'uploadDPID');
insert into adv_attrname (attrname_id, attrname) values (1407, 'uploadMAC');
insert into adv_attrname (attrname_id, attrname) values (1901, 'ifa1');
insert into adv_attrname (attrname_id, attrname) values (1902, 'ifa2');
insert into adv_attrname (attrname_id, attrname) values (1903, 'ifa3');
insert into adv_attrname (attrname_id, attrname) values (1904, 'ifa4');
insert into adv_attrname (attrname_id, attrname) values (1905, 'ip');
